version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/buildhelper/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
