name: Build wasm_exec.js
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup dependencies
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Build wasm_exec.js
        run: make wasm_exec

      - name: Publish to github pages  # Will also upload the artifact
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist-wasm_exec
          destination_dir: wasm_exec
          commit_message: "wasm_exec: ${{ github.event.head_commit.message }}"
