name: Build Go Compiler and frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17' ] # TODO: More Go versions
    name: Build Go Compiler and frontend (Go ${{ matrix.go }})
    steps:
      - uses: actions/checkout@v3

      # Setup dependencies
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install binaryen (wasm-opt tool)
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_105/binaryen-version_105-x86_64-linux.tar.gz | tar xzf -
          echo `pwd`/binaryen-*/bin | tee /dev/stderr >> $GITHUB_PATH

      - name: Build compiler and frontend
        run: make

      - uses: actions/upload-artifact@v3
        with:
          name: dist-go${{ matrix.go }}
          path: dist/
