name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17' ] # TODO: More Go versions
    name: Build Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2

      # Setup dependencies
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install binaryen (for wasm-opt tool)
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_105/binaryen-version_105-x86_64-linux.tar.gz | tar xzf -
          echo "`pwd`/binaryen-*/bin" > $GITHUB_PATH

      - name: Build compiler and frontend
        run: make

      - name: Create tarball from production build
        id: archive
        run: |
          set -ex
          VERSION=$GITHUB_REF_NAME
          PKGNAME="static-go-playground-$VERSION"
          TARBALL="$PKGNAME.tar.gz"
          SHASUM="$PKGNAME.tar.gz.sha256"
          cd dist/ && tar -czf "../$TARBALL" .
          cmake -E sha256sum $TARBALL > $SHASUM
          echo "::set-output name=tarball::$TARBALL"
          echo "::set-output name=shasum::$SHASUM"

      - name: Upload tarball as draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ${{ steps.archive.outputs.tarball }}
            ${{ steps.archive.outputs.shasum }}
