name: Build wasm_exec.js
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup dependencies
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build wasm_exec.js
        run: make wasm_exec

      - uses: actions/upload-artifact@v3
        with:
          name: wasm_exec
          path: dist-wasm_exec
          if-no-files-found: error
