name: Build Go Compiler and frontend
on:
  workflow_run: # Wait for wasm_exec.js to be built to avoid races when writing to github-pages
    workflows: [ "Build wasm_exec.js" ]
    types:
      - completed
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.14', '1.15', '1.16', '1.17', '1.18', '1.19' ]
    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3

      # Setup dependencies
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install binaryen (wasm-opt tool)
        if: ${{ matrix.go == '1.19' }} # Only optimize the builds on latest Go (takes a while)
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_105/binaryen-version_105-x86_64-linux.tar.gz | tar xzf -
          echo `pwd`/binaryen-*/bin | tee /dev/stderr >> $GITHUB_PATH

      - name: Build compiler and frontend
        run: make

      - name: Write GitHub Pages readme
        if: ${{ matrix.go == '1.19' }} && github.ref == 'refs/heads/main' # Only prepare GitHub pages for latest Go version and main branch
        run: |
          cat >dist/README.md <<EOF
          # Production build (${{github.ref_name}})
          
          To deploy on your own static web server, you just need to copy these files as needed:
          
          - Full app: The files in the root folder (without any subfolders or .nojekyll).
          - [wasm_exec.js](wasm_exec/wasm_exec.js): The subfolder wasm_exec is the standalone wasm_exec.js demo.
          
          The hosted version of the full app is available at https://${GITHUB_REPOSITORY}.github.io/ and the 
          wasm_exec.js standalone demo is available at https://${GITHUB_REPOSITORY}.github.io/wasm_exec/.
          
          \`\`\`
          Date: $(date +%F)
          Git revision: $(git rev-parse HEAD)
          \`\`\`
          EOF

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ matrix.go == '1.19' }} && github.ref == 'refs/heads/main' # Only prepare GitHub pages for latest Go version and main branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          keep_files: true  # Keep wasm_exec/* files
          commit_message: "Full app: ${{ github.event.head_commit.message }}"
